### ISSUE TITLE
Failed to connect: Access to the specified native messaging host is forbidden.

### ISSUE THREAD

**Issue by ludeen007** [PaulBenMarsh/nativeMessagingAPI-QTNative#1]
The actual chrome-extension id is different from the one specified in com.google.chrome.qtnative.echo-win.json.
When I run the example directly, the extension show the error as follows:
Failed to connect: Access to the specified native messaging host is forbidden.

When I replace the latter with the former, the example works like a charm.
Thanks.

**Comment by PaulBenMarsh** [comment]
Thanks for the feedback! Glad it's working for you.
I'll update the JSON and the readme to make it more obvious that the extension ID needs to be replaced.
